# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [1]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
%pip install --upgrade selenium
%pip install webdriver-manager

Requirement already satisfied: selenium in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.48.0)
Requirement already satisfied: certifi>=2026.2.25 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (2026.7.22)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (0.34.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.18)
Requirement already satisfied: outcome in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.1.1)
Requirement already satisfied: wsproto>=0.14 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: webdriver-manager in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.1.2)
Requirement already satisfied: requests in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from webdriver-manager) (2.34.2)
Requirement already satisfied: python-dotenv in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from webdriver-manager) (1.2.3)
Requirement already satisfied: packaging in C:\Users\52068085801\AppData\Roaming\Python\Python314\site-packages (from webdriver-manager) (26.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

#### Passo 2: Importar bibliotecas

In [2]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para gerenciar o serviço do ChromeDriver (processo em segundo plano que controla o Chrome)
# - Iniciar/parar o ChromeDriver
# - Configurar opções de execução
# - Gerenciar portas e processos
# - Definir caminhos do executável
from selenium.webdriver.chrome.service import Service 

# Módulo para gerenciamento do ChromeDriver:
# - Baixa automaticamente a versão correta do ChromeDriver
# - Verifica e atualiza drivers desatualizados
# - Elimina a necessidade de baixar manualmente o driver
# - Gerencia compatibilidade de versões
from webdriver_manager.chrome import ChromeDriverManager 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By # importa de

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys # botão (tecla)

#### Passo 3: Criar navegador

In [19]:
#driver = webdriver.Chrome(service=Service(ChromeDriverManager().install())) 
driver = webdriver.Chrome()

#### Passo 4: Acessar site

In [20]:
driver.get('https://pubmed.ncbi.nlm.nih.gov/') #digita o link automaticamente no navegador que estou usando

#### Passo 5: Fechar navegador

In [17]:
driver.quit()

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [21]:
driver = webdriver.Chrome()
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### 6.2: Selecionar o campo de busca pelo id

In [24]:
campo_busca = driver.find_element(By.ID, 'id_term') #By é por onde? (id, nome)

#### 6.3: Escrever um texto no campo de busca

In [25]:
campo_busca.send_keys('Pokemon')

#### 6.4: Clicar no Botão Pesquisar

In [26]:
driver.find_element(By.CLASS_NAME, 'search-btn').click() #clica no botão de busca

#### 6.5: Fechar navegador

In [27]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [28]:
# Criar navegador e acessar site
driver = webdriver.Chrome()
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

# Selecionar o campo de busca pelo id
campo_busca = driver.find_element(By.ID, 'id_term')

# Escrever um texto no campo de busca + Enter para iniciar busca
campo_busca.send_keys('pokemon', Keys.ENTER) #escreve e clica enter

# Listar todos os resultados
resultados = driver.find_elements(By.CLASS_NAME, 'full-docsum') # Atenção para a função find_elements (no plural)
print('Total de resultados:', len(resultados))

Total de resultados: 10

#### 7.1: Listar o título de todos os resultados

In [29]:
lista_de_titulos = []
for i in resultados:
    lista_de_titulos.append(i.find_element(By.CLASS_NAME, 'docsum-title').text)   
lista_de_titulos

['Primary Care: Its Pokemon Moment.',
 'Impact of Pokemon Go on Physical Activity: A Systematic Review and Meta-Analysis.',
 'Effects of Pokemon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review.',
 'Influence of Pokemon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review.',
 'Going Forward with Pokemon Go.',
 'Pokemon contagion.',
 'Random forests, sound symbolism and Pokemon evolution.',
 'Pokemon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians.',
 'Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms.',
 'Pokemon GO and Physical Activity in Asia: Multilevel Study.']

#### 7.2: Listar o link de todos os resultados

In [30]:
lista_de_links = []
for j in resultados:
    link = j.find_element(By.CLASS_NAME, "docsum-title").get_attribute("href") # a classe ainda é docsum-title, o get_attribute ('href')é olink
    lista_de_links.append(link)

lista_de_links

['https://pubmed.ncbi.nlm.nih.gov/38556037/',
 'https://pubmed.ncbi.nlm.nih.gov/31836333/',
 'https://pubmed.ncbi.nlm.nih.gov/33922978/',
 'https://pubmed.ncbi.nlm.nih.gov/37955949/',
 'https://pubmed.ncbi.nlm.nih.gov/30568365/',
 'https://pubmed.ncbi.nlm.nih.gov/11811868/',
 'https://pubmed.ncbi.nlm.nih.gov/36598905/',
 'https://pubmed.ncbi.nlm.nih.gov/27479151/',
 'https://pubmed.ncbi.nlm.nih.gov/39095579/',
 'https://pubmed.ncbi.nlm.nih.gov/29907559/']

#### 7.3: Acessar um dos links

In [14]:
# Por exemplo o link listado na primeira posição da lista_de_links
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

##### 1) Título

In [ ]:
driver.get(lista_de_links[0])
titulo = driver.find_element(By.CLASS_NAME,'heading-title').text
print(f'titulo: {titulo}')

titulo: Primary Care: Its Pokemon Moment

##### 2) Autores

In [34]:
driver.find_element(By.CLASS_NAME,'authors-list').text

'Bryan Becker  1'

##### 3) Ano de publicação

In [ ]:
driver.find_element(By.CLASS_NAME,'cit').text

'2024 Jul;137(7):577-581.'

##### 4) DOI

In [38]:
driver.find_element(By.CLASS_NAME,'id-link').text

'10.1016/j.amjmed.2024.03.020'

In [51]:
driver.find_element(By.XPATH,'//*[@id="full-view-identifiers"]/li[2]/span/a')

##### 5) Tipo de publicação

In [45]:
driver.find_element(By.CLASS_NAME,'keywords-list').text

'Review'

##### 6) Resumo

In [43]:
driver.find_element(By.CLASS_NAME,'keyword-actions-trigger').text

'Review'

##### 7) Link de acesso (como registro de referência)

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [52]:
colunas = ['titulos','autores','ano','doi','tipo de publicacao','resumo','links']
tabela = pd.DataFrame(columns=colunas)
tabela

Empty DataFrame
Columns: [titulos, autores, ano, doi, tipo de publicacao, resumo, links]
Index: []

#### 2) Obter dados dos links e armazenar na tabela

In [53]:
driver = webdriver.Chrome() # Criar navegador

id = 0 # Contador
for j in lista_de_links:
    try:

        # Acessa o link
        driver.get(j)
        
        # Título
        try:
            titulo = driver.find_element(By.CLASS_NAME, 'heading-title').text
        except: 
            titulo = None
            print(f'Link: {id} - Não foi possível obter o título')
        
        # Autores
        try:
            autores = driver.find_element(By.CLASS_NAME, 'authors-list').text
        except: 
            autores = None
            print(f'Link: {id} - Não foi possível obter os autores')
            
        # Ano de publicação
        try:
            ano = driver.find_element(By.CLASS_NAME, 'cit').text.split()[0]
        except: 
            ano = None
            print(f'Link: {id} - Não foi possível obter o ano')
            
        # DOI
        try:
            doi = driver.find_element(By.CLASS_NAME, 'id-link').text
        except: 
            doi = None
            print(f'Link: {id} - Não foi possível obter o DOI')
            
        # Tipo de publicação
        try:
            tipo = driver.find_element(By.CLASS_NAME, 'keyword-actions-trigger').text
        except: 
            tipo = None
            print(f'Link: {id} - Não foi possível obter o Tipo de Pesquisa')
            
        # Resumo
        try:
            resumo = driver.find_element(By.ID, 'eng-abstract').text
        except: 
            resumo = None
            print(f'Link: {id} - Não foi possível obter o Resumo')
            
        # Link
        link = j
        
        # Insere uma nova linha na tabela com as informações do produto
        tabela.loc[len(tabela)] = [titulo,autores,ano,doi,tipo,resumo,link]

        print(f'Link: {id} - Raspagem concluída com sucesso')
        #driver.quit()

    except:
        print(f'Link: {id} - Não foi possível obter os dados solicitados')

    # Incrementa uma posição no contador
    id = id+1

Link: 0 - Não foi possível obter o título
Link: 0 - Não foi possível obter os autores
Link: 0 - Não foi possível obter o ano
Link: 0 - Não foi possível obter o DOI
Link: 0 - Não foi possível obter o Tipo de Pesquisa
Link: 0 - Não foi possível obter o Resumo
Link: 0 - Raspagem concluída com sucesso
Link: 1 - Não foi possível obter o título
Link: 1 - Não foi possível obter os autores
Link: 1 - Não foi possível obter o ano
Link: 1 - Não foi possível obter o DOI
Link: 1 - Não foi possível obter o Tipo de Pesquisa
Link: 1 - Não foi possível obter o Resumo
Link: 1 - Raspagem concluída com sucesso
Link: 2 - Raspagem concluída com sucesso
Link: 3 - Raspagem concluída com sucesso
Link: 4 - Raspagem concluída com sucesso
Link: 5 - Não foi possível obter o Resumo
Link: 5 - Raspagem concluída com sucesso
Link: 6 - Raspagem concluída com sucesso
Link: 7 - Raspagem concluída com sucesso
Link: 8 - Raspagem concluída com sucesso
Link: 9 - Raspagem concluída com sucesso

#### 3) Visualizar tabela

In [54]:
tabela

,titulos,autores,ano,doi,tipo de publicacao,resumo,links
0,NaN,NaN,NaN,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/38556037/
1,NaN,NaN,NaN,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/31836333/
2,Effects of Pokémon GO on Physical Activity and...,"Jung Eun Lee 1 , Nan Zeng 2 , Yoonsin Oh 3 ...",2021,PMC8123321,Review,"Augmented reality (AR) mobile game, Pokémon GO...",https://pubmed.ncbi.nlm.nih.gov/33922978/
3,Influence of Pokémon GO on Physical Activity a...,"Haiyan Liang 1 , Xi Wang 2 , Ruopeng An 2",2023,PMC10682915,Systematic Review,"Background: Pokémon GO, an augmented reality g...",https://pubmed.ncbi.nlm.nih.gov/37955949/
4,Going Forward with Pokemon Go,"Yvette Chong 1 , Dean Krishen Sethi 1 , Char...",2018,PMC6262652,Review,Pokemon Go is an augmented reality (AR) game w...,https://pubmed.ncbi.nlm.nih.gov/30568365/
5,Pokemon contagion,"B G Zifkin, D G Kasteleijn-Nolst Trenité",2001,10.1097/00007611-200112000-00025,Comment,NaN,https://pubmed.ncbi.nlm.nih.gov/11811868/
6,"Random forests, sound symbolism and Pokémon ev...","Alexander James Kilpatrick 1 , Aleksandra Ćwi...",2023,PMC9812336,"Research Support, Non-U.S. Gov't",This study constructs machine learning algorit...,https://pubmed.ncbi.nlm.nih.gov/36598905/
7,Pokémon Go and augmented virtual reality games...,"Maeve Serino 1 , Kyla Cordrey, Laura McLaughl...",2016,10.1097/MOP.0000000000000409,Review,Purpose of review: The recent release of Pokém...,https://pubmed.ncbi.nlm.nih.gov/27479151/
8,Pokemon inhibits Bim transcription to promote ...,"Yan Wang # 1 2 , Huiling Zeng # 1 , Li Li ...",2024,PMC11297103,Aged,Purpose: This study aims to determine whether ...,https://pubmed.ncbi.nlm.nih.gov/39095579/
9,Pokémon GO and Physical Activity in Asia: Mult...,"Ben D Ma 1 2 , Sai Leung Ng 1 , Tim Schwan...",2018,PMC6026299,Adolescent,Background: Physical activity has long been co...,https://pubmed.ncbi.nlm.nih.gov/29907559/

#### 4) Exportar DataFrame para Excel

In [55]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [57]:
tabela.to_excel('tabela_raspagem.xlsx',index=False)