# **EDA NFL 2009-2017**
Neste dataset, temos informações sobre os jogos da NFL entre 2009 e 2017. O objetivo desta análise, é explorar os dados, identificar os padrões, tendências e insights que possam ser extraídos. Implementaremos todas as etapas da arquitetura medalhão, onde cada camada representa um nível de processamento e transformação dos dados, permitindo uma análise mais profunda e estruturada.
O intuito é extrair quais times tiveram melhor desempenho, quais jogadores se destacaram, quais estratégias foram mais eficazes e como os resultados variaram ao longo dos anos.

## Objetivo da análise
O objetivo desta análise é explorar os dados da NFL entre 2009 e 2017, identificando padrões, tendências e insights que possam ser extraídos. Em pról de fornecer informações sobre o desempenho dos times, jogadores e estratégias utilizadas no esporte dentro da NFL.

### O que foi utilizado neste notebook?
O notebook atual é composto por análises realizadas em dois outros notebooks aplicados em sala de aula (`Pre_processamento_dados_2`) e (`Pre_processamento_dados_gabarito`) na versão atual, não foi utilizada a biblioteca `kagglehub`. O arquivo .CSV foi utilizado para a análise.

In [1]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (26.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Bibliotecas Utilizadas

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pyarrow
from pathlib import Path

c:\Users\52068085801\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Importando arquivo CSV

In [3]:
df = pd.read_csv('NFL_2009_2017.csv')

C:\Users\52068085801\AppData\Local\Temp\ipykernel_2064\2127144522.py:1: DtypeWarning: Columns (25: DefTwoPoint, 51: BlockingPlayer) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('NFL_2009_2017.csv')

## Diagnóstico inicial
Visualizar o tipo dos daods, o nome das colunas, verifcando ausentes e duplicados, os primeiros e últimos registros. Anaálise inicial é importante para entender a estrutura do dataset e identificar possíveis problemas que possam afetar a própria análise, entender como reduzir o tamanho da consulta geral, e como otimizar a análise.

In [9]:
print(df.shape) #total de linhas e colunas do dataset

(407688, 102)

In [10]:
df.head(5) #visualizar os primeiros 5 registros do dataset

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [11]:
df.tail(5) #visualizar os últimos 5 registros do dataset

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
407683,2017-12-31,2017123101,29,4,NaN,00:28,1,28.0,4.0,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,2017
407684,2017-12-31,2017123101,29,4,3.0,00:28,1,28.0,0.0,BAL,...,-0.397515,0.080409,0.919591,0.050478,0.949522,0.080409,-0.029931,-0.021795,-0.008136,2017
407685,2017-12-31,2017123101,29,4,4.0,00:24,1,24.0,4.0,BAL,...,2.457114,0.050478,0.949522,0.030881,0.969119,0.050478,-0.019597,-0.030603,0.011006,2017
407686,2017-12-31,2017123101,30,4,1.0,00:14,1,14.0,10.0,BAL,...,NaN,0.030881,0.969119,0.000000,1.000000,0.969119,0.030881,NaN,NaN,2017
407687,2017-12-31,2017123101,30,4,NaN,00:00,0,0.0,14.0,BAL,...,NaN,0.000000,1.000000,0.000000,1.000000,0.999159,0.000000,NaN,NaN,2017

## Tamanho do dataset:
Foi utilizado df.info(memory_usage='deep') para obter informações sobre o dataset, incluindo tipos de dados e uso de memória. Identificamos os tipos float64 e int64, que são tipos de dados numéricos e object, que são tipos de dados pesados.

In [ ]:
df.info(memory_usage='deep') #informações sobre o dataset, incluindo tipos de dados e uso de memória

<class 'pandas.DataFrame'>
RangeIndex: 407688 entries, 0 to 407687
Columns: 102 entries, Date to Season
dtypes: float64(33), int64(31), str(38)
memory usage: 380.5 MB

### Tamanho do CSV atual:

In [13]:
print('Tamanho do CSV (em MB):', round(os.path.getsize('NFL_2009_2017.csv') / (1024 * 1024), 2)) #tamanho do CSV em MB

Tamanho do CSV (em MB): 262.77